### ISSUE TITLE
Specifying place to move fails using capital letters

### ISSUE THREAD

**Issue by dirtyvagabond** [thomascpan/chess#2]
Lower-case works, but capitals result in a crash. This is somewhat confusing, since the board is displayed using all caps. Example:

```
$ ruby example/example_game.rb
Welcome to Chess!

 Do you want to (l)oad a game, (s)tart a new game, (d)elete a game, or (q)uit.
s
Input Format: Letter followed by Number. Ex.(a1)

Player_two(W) has randomly been selected to go first.
    A   B   C   D   E   F   G   H
8 [RB][kB][BB][QB][KB][BB][kB][RB]
7 [PB][PB][PB][PB][PB][PB][PB][PB]
6 [  ][  ][  ][  ][  ][  ][  ][  ]
5 [  ][  ][  ][  ][  ][  ][  ][  ]
4 [  ][  ][  ][  ][  ][  ][  ][  ]
3 [  ][  ][  ][  ][  ][  ][  ][  ]
2 [PW][PW][PW][PW][PW][PW][PW][PW]
1 [RW][kW][BW][QW][KW][BW][kW][RW]
player_two(W): Please select a piece. (enter 'save' to save the game or 'menu' to return back to menu)
E2
/private/tmp/chess/lib/chess/game.rb:104:in `[]': no implicit conversion from nil to integer (TypeError)
    from /private/tmp/chess/lib/chess/game.rb:104:in `get_move'
    from /private/tmp/chess/lib/chess/game.rb:42:in `game_control'
    from /private/tmp/chess/lib/chess/game.rb:35:in `new_game'
    from /private/tmp/chess/lib/chess/game.rb:21:in `menu'
    from example/example_game.rb:6:in `<main>'
```

**Comment by thomascpan** [comment]
Thanks again mate! 

Fixed bug. 

Made all command case-insensitive. 

Thanks!

**Comment by dirtyvagabond** [comment]
works for me, thanks for the fix!  :+1:
